### PR TITLE
Alcole calculus made easy

### PR DESCRIPTION
**Pull request by alcole**
Added Calculus Made Easy by Silvanus P. Thompson, hosted on Gutenberg.org

Also, tidied link spacing for MIT Calculus book

### CODE REVIEW

**Comment by eshellman** [comment]
isn't the gutenberg title available in epub and mobi as well?

**Comment by alcole** [comment]
I could only see .pdf and .tex listed here: http://www.gutenberg.org/ebooks/33283

**Comment by eshellman** [comment]
Hmmm. I'm playing with the PG ebook renderer right now. Might be interesting to see whether latex2html works on it!

**Comment by eshellman** [comment]
I guess the TODO is one of the to-dos!

**Pull request merged**
