### PR TITLE
UPDATE RE: Alphabetized the names, and added resources into Natural History, Zoology, Human Anatomy, Physiology, Microbiology, Nursing

### PR DESCRIPTION
**Pull request by kree666**
Moved Microbiology up and added in a new microbiology book.

## What does this PR do?
Add Resource and moved the microbiology category up to where it fit alphabetically in the list.
Requesting this PR add an "hacktoberfest-accepted" to it for Hacktoberfest once approved. 
It's showing as an Ineligible Repository because it's labeled as "hacktoberfest2020" and not labeled as "hacktoberfest"

### Description 
Added Microbiology - Nina Parker, Mark Schneegurt, Philip Lister et all. (PDF)

### Why is this valuable (or not)
It's a free microbiology book

### How do we know it's really free?
It's on OpenStax, and you can download the entire book as a PDF without using an email.

### For book lists, is it a book?
Yes

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
With regard to ordering categories, we've chosen to use Library of Congress codes to set alphabetical order for this repo. The OpenStax book is fine

**Comment by eshellman** [comment]
changed the hacktoberfest tag

**Comment by kree666** [comment]
@eshellman Regarding the ordering of the list. I was unsure about what to do with the sections in the 'sections to add' area that don't have books yet because they go in the middle of the Q & T sections. 
Should I still move them up to where they should be in the list so that they are all alphabetical even though they don't have books yet? 
Sorry, it's why I just moved the QR section up to where it goes in the list.

**Comment by eshellman** [comment]
This seems reasonable. Thanks!

**Comment by eshellman** [comment]
maybe add pubyears to the older resources?

**Pull request merged**
